# for each community designation, what proportion of the daily VMT is related to commute trips?
# commute trips are the primary work location, not work related trips more generally
# for weighting
# calculate VMT per linked trip (linked trip weight)
# then use the trip purpose weight to weight the VMT across trip purposes
# use HH community designation to group by community designation
#
# The goal is to use the to estimate the percentage of VMT within each community
# designation that is commuting, so that we can target workplace trip reduction
# programs.
#
# we could use the origin trip CD or the destination CD, and assign a workplace
# CD based on the O or D trip purpose.
#
# Howver, we still have to calculate the total VMT that occurred in each CD
# this is regardless of origin or destination (right?)
# so then how do we join that with a specific CD?
#
# We could stick with the HH CD, which would mean that we are calculating
# the proportion of all VMT generated by households that live in each CD
# that is commute. The numerator and denominator are in the same universe,
# the same pool
#

pkgload::load_all()
source("data-raw/transportation_data_processing/_tbi_load.R")
library(srvyr)

valid_trips <- trip %>%
  filter(
    hh_id %in% hh_region$hh_id,
    mode_type %in% c(
      "Household Vehicle",
      "Other Vehicle",
      "For-Hire Vehicle"
    ),
    # origin and destination in MPO area
    trip_o_in_mpo == TRUE,
    trip_d_in_mpo == TRUE,
    # ensure observed trip duration,
    # reasonable distance
    # origin or destination in our counties
    duration_seconds > 0,
    as.character(trip_o_county) %in% cprg_tbi_hh_counties,
    as.character(trip_d_county) %in% cprg_tbi_hh_counties,
    distance_miles < 720,
    distance_miles > 0,
    !is.na(num_travelers_int)
  ) %>%
  left_join(hh_region, join_by(survey_year, hh_id)) %>%
  filter(
    linked_trip_weight > 0,
    !is.na(cd_2050)
  ) %>%
  # left_join(days, join_by(survey_year, hh_id, person_id, day_id, day_num)) %>%
  left_join(trip_purpose, by = join_by(linked_trip_id, hh_id, person_id, day_id, day_num, survey_year)) %>%
  mutate(
    vmt = distance_miles / num_travelers_int,
    weighted_vmt = vmt * linked_trip_weight
  ) %>%
  filter(!is.na(trip_purpose_weight)) %>%
  select(survey_year, linked_trip_id, linked_trip_weight, cd_2050_broad, purpose_category,
         d_purpose, o_purpose, trip_d_cd_2050_broad, trip_o_cd_2050_broad,
         vmt, weighted_vmt)

trip_commute_vmt <- valid_trips %>%
  # filter(o_purpose== "Went home" & d_purpose== "Primary workplace" |
  #          o_purpose == "Primary workplace" & d_purpose == "Went home") %>%
  # mutate(workplace_cd = case_when(d_purpose == "Primary workplace" ~ trip_d_cd_2050_broad,
  #                                 o_purpose == "Primary workplace" ~ trip_o_cd_2050_broad)) %>%
  filter(purpose_category == "Work") %>%
  group_by(cd_2050_broad) %>%
  as_survey_design(weights = linked_trip_weight) %>%
  summarise(
    commute_vmt = survey_total(vmt, vartype = "se"),
    commute_count = n(),
    .groups = "keep"
  )


trip_vmt <- valid_trips %>%
  group_by(cd_2050_broad) %>%
  as_survey_design(weights = linked_trip_weight) %>%
  summarise(
    total_vmt = survey_total(vmt, vartype = "se"),
    total_count = n(),
    .groups = "keep"
  )


tbi_commute_vmt_prop <- left_join(trip_commute_vmt, trip_vmt, join_by(cd_2050_broad)) %>%
  mutate(
    commute_vmt_prop = commute_vmt / total_vmt,
    commute_count_prop = commute_count / total_count
  ) %>%
  select(
    cd_2050_broad,
    commute_vmt,
    total_vmt,
    commute_vmt_prop,
    commute_count,
    total_count,
    commute_count_prop
  )

# about 12% of trips, 20% of VMT
tbi_commute_vmt_prop
