# for each community designation, what proportion of the daily VMT is related to commute trips?
# commute trips are the primary work location, not work related trips more generally
# for weighting
# calculate VMT per linked trip (linked trip weight)
# then use the trip purpose weight to weight the VMT across trip purposes
# use HH community designation to group by community designation
#
# The goal is to use the to estimate the percentage of VMT within each community
# designation that is commuting, so that we can target workplace trip reduction
# programs.
#
# we could use the origin trip CD or the destination CD, and assign a workplace
# CD based on the O or D trip purpose.
#
# However, we still have to calculate the total VMT that occurred in each CD
# this is regardless of origin or destination
# so then how do we join that with a specific CD?
#
# We could stick with the HH CD, which would mean that we are calculating
# the proportion of all VMT generated by households that live in each CD
# that is commute. The numerator and denominator are in the same universe,
# the same pool
#

pkgload::load_all()
source("data-raw/transportation_data_processing/_tbi_load.R")
library(srvyr)

valid_trips <- trip %>%
  filter(
    hh_id %in% hh_region$hh_id,
    mode_type %in% c(
      "Household Vehicle",
      "Other Vehicle",
      "For-Hire Vehicle"
    ),
    # origin and destination in MPO area
    trip_o_in_mpo == TRUE,
    trip_d_in_mpo == TRUE,
    # ensure observed trip duration,
    # reasonable distance
    # origin or destination in our counties
    duration_seconds > 0,
    as.character(trip_o_county) %in% cprg_tbi_hh_counties,
    as.character(trip_d_county) %in% cprg_tbi_hh_counties,
    distance_miles < 720,
    distance_miles > 0,
    !is.na(num_travelers_int)
  ) %>%
  left_join(hh_region, join_by(survey_year, hh_id)) %>%
  filter(
    linked_trip_weight > 0,
    !is.na(cd_2050)
  ) %>%
  # left_join(days, join_by(survey_year, hh_id, person_id, day_id, day_num)) %>%
  left_join(trip_purpose, by = join_by(linked_trip_id, hh_id, person_id, day_id, day_num, survey_year)) %>%
  mutate(
    vmt = distance_miles / num_travelers_int,
    weighted_vmt = vmt * linked_trip_weight
  ) %>%
  filter(!is.na(trip_purpose_weight)) %>%
  select(
    survey_year, linked_trip_id, linked_trip_weight, cd_2050_broad, cd_2050, purpose_category,
    d_purpose, o_purpose, trip_d_cd_2050_broad, trip_o_cd_2050_broad,
    hh_county,
    vmt, weighted_vmt
  )

# first at the communty designation level -----
trip_commute_vmt <- valid_trips %>%
  filter(purpose_category == "Work") %>%
  group_by(cd_2050) %>%
  as_survey_design(weights = linked_trip_weight) %>%
  summarise(
    commute_vmt = survey_total(vmt, vartype = "se"),
    commute_count = n(),
    .groups = "keep"
  )


trip_vmt <- valid_trips %>%
  group_by(cd_2050) %>%
  as_survey_design(weights = linked_trip_weight) %>%
  summarise(
    total_vmt = survey_total(vmt, vartype = "se"),
    total_count = n(),
    .groups = "keep"
  )


tbi_commute_vmt_prop <- left_join(trip_commute_vmt, trip_vmt, join_by(cd_2050)) %>%
  mutate(
    commute_vmt_prop = commute_vmt / total_vmt,
    commute_count_prop = commute_count / total_count
  ) %>%
  select(
    cd_2050,
    commute_vmt,
    total_vmt,
    commute_vmt_prop,
    commute_count,
    total_count,
    commute_count_prop
  )


# compute at COUNTY level -----

trip_county_commute_vmt <- valid_trips %>%
  filter(purpose_category == "Work") %>%
  group_by(hh_county) %>%
  as_survey_design(weights = linked_trip_weight) %>%
  summarise(
    commute_vmt = survey_total(vmt, vartype = "se"),
    commute_count = n(),
    .groups = "keep"
  )

trip_county_vmt <- valid_trips %>%
  group_by(hh_county) %>%
  as_survey_design(weights = linked_trip_weight) %>%
  summarise(
    total_vmt = survey_total(vmt, vartype = "se"),
    total_count = n(),
    .groups = "keep"
  )

tbi_county_commute_vmt_prop <- left_join(trip_county_commute_vmt, trip_county_vmt, join_by(hh_county)) %>%
  mutate(
    commute_vmt_prop = commute_vmt / total_vmt,
    commute_count_prop = commute_count / total_count,
    geog_name = stringr::str_replace(hh_county, "MN", "County") %>%
      stringr::str_trim(),
    cd_2050 = "County"
  ) %>%
  select(
    geog_name,
    hh_county,
    cd_2050,
    commute_vmt,
    total_vmt,
    commute_vmt_prop,
    commute_count,
    total_count,
    commute_count_prop
  ) %>%
  left_join(geog_index %>% filter(geog_level == "COUNTY") %>% select(geog_name, geog_id) %>% unique(), join_by(geog_name)) %>%
  ungroup()


# compute at the region level -----
trip_region_commute_vmt <- valid_trips %>%
  filter(purpose_category == "Work") %>%
  as_survey_design(weights = linked_trip_weight) %>%
  summarise(
    commute_vmt = survey_total(vmt, vartype = "se"),
    commute_count = n(),
    .groups = "keep"
  )

trip_region_vmt <- valid_trips %>%
  as_survey_design(weights = linked_trip_weight) %>%
  summarise(
    total_vmt = survey_total(vmt, vartype = "se"),
    total_count = n(),
    .groups = "keep"
  )

tbi_region_commute_vmt_prop <- cbind(trip_region_commute_vmt, trip_region_vmt) %>%
  mutate(
    commute_vmt_prop = commute_vmt / total_vmt,
    commute_count_prop = commute_count / total_count,
    geog_name = "Twin Cities Region",
    geog_id = "00000000",
    cd_2050 = "Region"
  ) %>%
  select(
    geog_name,
    geog_id,
    cd_2050,
    commute_vmt,
    total_vmt,
    commute_vmt_prop,
    commute_count,
    total_count,
    commute_count_prop
  ) %>%
  left_join(geog_index %>% filter(geog_level == "REGION") %>% select(geog_name, geog_id) %>% unique(), join_by(geog_name, geog_id))


# compile final ----
commute_vmt_proportion <- tbi_commute_vmt_prop %>%
  select(cd_2050, commute_vmt_prop) %>%
  ungroup() %>%
  full_join(geog_index %>% filter(geog_id_type == "ctu_gnis"), join_by(cd_2050 == imagine_designation)) %>%
  bind_rows(tbi_county_commute_vmt_prop %>% select(geog_name, geog_id, cd_2050, commute_vmt_prop)) %>%
  bind_rows(tbi_region_commute_vmt_prop %>% select(geog_name, geog_id, cd_2050, commute_vmt_prop)) %>%
  mutate(
    mode = "PLDV",
    var = "COMMUTE_VMT_PROP",
    type = "P"
  ) %>%
  select(
    mode, var, geog_name,
    geog_id,
    value = commute_vmt_prop,
    type
  ) %>%
  arrange(geog_name)


usethis::use_data(commute_vmt_proportion, overwrite = TRUE)
