councilmembers <- data.frame(
  name = c(
    "Charlie Zelle",
    "Judy Johnson",
    "Reva Chamblis",
    "Christopher Ferguson",
    "Deb Barber",
    "Molly Cummings",
    "John Pacheco Jr.",
    "Robert Lilligren",
    "Abdirahman Muse",
    "Raymond Zeran",
    "Peter Lindstrom",
    "Susan Vento",
    "Francisco J. Gonzalez",
    "Chai Lee",
    "Kris Fredson",
    "Phillip Sterner",
    "Wendy Wulff",
    ""
  ),
  position = c(
    "Chair",
    "District 1",
    "District 2",
    "District 3",
    "District 4",
    "District 5",
    "District 6",
    "District 7",
    "District 8",
    "District 9",
    "District 10",
    "District 11",
    "District 12",
    "District 13",
    "District 14",
    "District 15",
    "District 16",
    ""
  )
)
