---
title: "Checks - Green Infrastructure & Land Use Module"
# author: Ellen
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Checks - Green Infrastructure & Land Use Module}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE,
                      comment = "#>")
options(rmarkdown.html_vignette.check_title = FALSE)

library(ghg.sp)
library(knitr)
```

# Intro

The goal here is to review the green infrastructure and land use models. Figure out the relative impact of each lever, make some plots to see if anything jumps out as needing to be fixed, etc. 


```{r get-ctu}
dl_ctu <- FALSE


if (dl_ctu == TRUE) {
  temp <- tempfile()
  download.file(
    "https://resources.gisdata.mn.gov/pub/gdrs/data/pub/us_mn_state_metc/society_thrive_msp2040_com_des/gpkg_society_thrive_msp2040_com_des.zip",
    destfile = temp
  )
  comdes <-
    sf::read_sf(unzip(temp, "society_thrive_msp2040_com_des.gpkg")) %>%
    # sf::st_drop_geometry() %>% count(CTU_NAME) %>% filter(n > 1) #there are some ctus with multiple designations; get the biggest one
    group_by(CTU_NAME) %>%
    mutate(max_area = max(Shape_Area)) %>%
    filter(Shape_Area == max_area)
  fs::file_delete("society_thrive_msp2040_com_des.gpkg")
}

```


```{r}
land_use_data$ctu_forecast

```
