---
title: "Adjust fleet shares"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{fleet_shares}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.width = 8
)
```

```{r setup}
requireNamespace("ggplot2", quietly = TRUE)
requireNamespace("scales", quietly = TRUE)
requireNamespace("councilR", quietly = TRUE)
requireNamespace("wesanderson", quietly = TRUE)
library(ghg.sp)
library(ggplot2)
library(dplyr)
library(stringr)
library(scales)
library(wesanderson)
library(councilR)

ggplot2::theme_set(
  if(testthat:::on_ci() == TRUE){
    theme_minimal()
  } else {
    councilR::theme_council(use_showtext = T,
                            use_manual_font_sizes = T)
  }
)


st_paul_pass <- transportation_data$passenger %>%
  filter(
    ctu %in% c(
      "St. Paul",
      "All"
    ),
    # !year %in% c("2045", "2050")
  )
st_paul_freight <- transportation_data$freight %>%
  filter(
    ctu %in% c(
      "St. Paul",
      "All"
    ),
    # !year %in% c("2045","2050")
  )

my_caption <- paste0(Sys.Date())
```


```{r}
adj_sales <- adj_fleet_shares(
  .pass_tb = transportation_data$passenger,
  .freight_tb = transportation_data$freight,
  .bev_pct_sales = 0.9,
  .hev_pct_sales = 0.05,
  .phev_pct_sales = 0.01
)
```

## Passenger vehicles  


```{r}
bau_pldv_sales <- transportation_data$passenger %>%
  filter(
    str_detect(var, "Sales"),
    mode == "PLDV",
    var != "TotSales"
  ) %>%
  group_by(year, var) %>% 
  summarize(value = sum(value)) %>% 
  mutate(scenario = "BAU") %>% 
  bind_rows(adj_sales$pass %>% 
              filter(
                str_detect(var, "Sales"),
                mode == "PLDV",
                var != "TotSales"
              ) %>%
              group_by(year, var) %>% 
              summarize(value = sum(value)) %>% 
              mutate(scenario = "Sales Adjusted"))




ggplot(data = bau_pldv_sales, 
       aes(
         x = year,
         y = value,
         color = var,
         fill = var,
         group = var
       )) +
  facet_wrap(~scenario ) +
  geom_area() +
  scale_fill_manual(
    name = "Powertrain",
    values = wesanderson::wes_palettes$Royal2,
    aesthetics = c("fill", "color"),
    labels = c(
      "BEVSales" = "Electric",
      "CISales" = "Diesel",
      "HEVSales" = "Hybrid",
      "PHEVSales" = "Plug-in hybrid",
      "SISales" = "Gasoline"
    )
  ) +
  scale_y_continuous(labels = scales::comma) +
  labs(title = "Passenger personal vehicle sales",
       y = "Sales") 

```

```{r}
bau_pldv_stock <- transportation_data$passenger %>%
  filter(
    str_detect(var, "Stock"),
    mode == "PLDV",
    var != "TotStock"
  ) %>%
  ungroup() %>%
  group_by(year, var) %>% 
  summarize(value = sum(value)) %>% 
  mutate(scenario = "BAU") %>% 
  bind_rows(adj_sales$pass %>% 
              filter(
                str_detect(var, "Stock"),
                mode == "PLDV",
                var != "TotStock"
              ) %>%
              group_by(year, var) %>% 
              summarize(value = sum(value)) %>% 
              mutate(scenario = "Sales Adjusted"))



ggplot(data = bau_pldv_stock,
       aes(
         x = year,
         y = value,
         color = var,
         fill = var,
         group = var
       )) +
  geom_area() +
  facet_wrap(~scenario) +
  # geom_area(position = "fill") +
  scale_fill_manual(
    name = "Powertrain",
    values = wesanderson::wes_palettes$Royal2,
    aesthetics = c("fill", "color"),
    labels = c(
      "BEVStock" = "Electric",
      "CIStock" = "Diesel",
      "HEVStock" = "Hybrid",
      "PHEVStock" = "Plug-in hybrid",
      "SIStock" = "Gasoline"
    )
  ) +
  scale_y_continuous(labels = scales::comma) +
  labs(title = "Passenger personal vehicle stock",
       y = "Vehicles")

```

## Transit vehicles    

```{r}

bu_stock <- 
  transportation_data$passenger %>%
  filter(
    str_detect(var, "Stock"),
    mode == "BU",
    var != "TotStock"
  ) %>%
  group_by(year, var) %>% 
  summarize(value = sum(value)) %>%   
  mutate(scenario = "BAU") %>% 
  bind_rows(adj_sales$pass %>%
              filter(
                str_detect(var, "Stock"),
                mode == "BU",
                var != "TotStock"
              ) %>%
              group_by(year, var) %>% 
              summarize(value = sum(value)) %>%   
              mutate(scenario = "Sales Adjusted"))


ggplot(bu_stock, 
       aes(
  x = year,
  y = value,
  color = var,
  fill = var,
  group = var
)) +
  geom_area(position = "stack") +
  facet_wrap(~scenario)+
  # geom_area(position = "fill") +
  scale_fill_manual(
    name = "Powertrain",
    values = wesanderson::wes_palettes$Royal2,
    aesthetics = c("fill", "color"),
    labels = c(
      "BEVStock" = "Electric",
      "CIStock" = "Diesel",
      "HEVStock" = "Hybrid",
      "PHEVStock" = "Plug-in hybrid",
      "SIStock" = "Gasoline",
      "BCIStock" = "Diesel"
    )
  ) +
  scale_y_continuous(labels = scales::comma) +
  labs(title = "Bus vehicle stock",
       y = "Vehicles",
       x = "Year")  +
  theme(legend.position = "bottom")


```


```{r}

bus_stock_total <- bu_stock %>% 
  filter(scenario == "BAU") %>% 
  group_by(year, scenario) %>% 
  summarize(value = round(sum(value)))

ggplot(bu_stock %>% 
         filter(scenario == "BAU"), 
       aes(
  x = year,
  y = value,
  color = var,
  fill = var,
  group = var
)) +
  geom_area(position = "stack") +
  # facet_wrap(~scenario)+
  # geom_area(position = "fill") +
  scale_fill_manual(
    name = "Powertrain",
    values = wesanderson::wes_palettes$Royal2,
    aesthetics = c("fill", "color"),
    labels = c(
      "BEVStock" = "Electric",
      "CIStock" = "Diesel",
            "BCIStock" = "Diesel",
      "HEVStock" = "Hybrid",
      "PHEVStock" = "Plug-in hybrid",
      "SIStock" = "Gasoline"
    )
  ) +
  scale_y_continuous(labels = scales::comma) +
  geom_point(
    inherit.aes = FALSE,
    data = bus_stock_total,
            aes(x = year,
                y = value)) +
  geom_text(
    inherit.aes = FALSE,
    data = bus_stock_total,
            aes(x = year,
                y = value,
                label =  value),
    nudge_y = 80) +
  labs(title = "Bus vehicle stock",
       y = "Vehicles",
       x = "Year",
       caption = paste0(my_caption, " Source: Metro Transit Facts and National Transit Database"))  +
  theme(legend.position = "bottom")

ggsave("../data-raw/peer_review/figs/bus_stock.png",
      width = 10,
      height = 8)
```

