---
title: "Interventions"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{intervention_overview}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  fig.width = 8
)

requireNamespace("ggplot2", quietly = TRUE)
requireNamespace("scales", quietly = TRUE)
requireNamespace("councilR", quietly = TRUE)
requireNamespace("wesanderson", quietly = TRUE)
library(ghg.sp)
library(ggplot2)
library(dplyr)
library(stringr)
library(scales)
library(wesanderson)
library(councilR)
library(emo)

ggplot2::theme_set(
  if(testthat:::on_ci() == TRUE){
    theme_minimal()
  } else {
      councilR::theme_council(use_showtext = T,
                          use_manual_font_sizes = T)
  }
)

```


# Intervention strategies

All possible strategies  

## Transportation  

There are two main transportation strategies: vehicle electrification and increase public transit.  

### Increase public transit  

- Land use changes  
- Increase average vehicle occupancy using route improvements  
- 


**VMT effects - negative coefficients**   
Increase in these values = decrease in PLDV VMT

- Vehicle-miles-traveled fee   
- Pay-as-you-drive fee   
- Gas tax  
- Parking price increases  
- Telework
- Land use changes (no more than a 25% reduction in VMT)
    - + Employment density, jobs per sq. mi. developed land  
    - + Housing density, residents per sq. mi. developed land  
    - + Land use diversity / entropy  
    - + Intersection design (increase % of intersections with 3+ ways)
    - - Minimum distance to transit stop from residential building   
    - + Job accessibility via transit (jobs located within one mile of the home)
- Transit ridership  
- Average vehicle occupancy  
- Vehicle automation  
- Dynamic ride sharing (contextual)  
- Annual energy outlook (contextual)
    
  
