### Urban Tree Planting

Trees in urban areas have a high concentration of carbon stored in their canopies and are often the largest source of biogenic carbon in an urban ecosystem. By increasing the tree canopy in cities, it is possible to offset some carbon emissions and also provide other benefits, such as reducing energy costs for cooling and improving subjective well-being.

A mature urban forest can hold up to 115 Mg of carbon per hectare. Additionally, a tree that grows for one year can sequester carbon annually at a rate of 1.27 Mg of carbon per hectare per year. Both of these processes are included in the scenario planning model, which shows that urban reforestation can contribute significantly to a carbon sink, provided there is enough land for reforestation. This is likely to be more feasible in suburban communities than in central cities. However, it is important to note that urban trees grow quickly but may also die young. As a result, to maximize the potential carbon mitigation from urban reforestation, careful tree management and an understanding of the life cycle of urban forestry is necessary.

Many initiatives have been launched globally, including the Trillion Trees Initiative, which aims to restore forests in order to slow down climate change. Some cities, such as Los Angeles, have also launched projects to plant large numbers of trees, with the *Los Angeles Million Trees Plan* estimating that up to 2.5 million trees could potentially be planted in the city. Recently, the City of Tucson announced a plan to plant one million trees by 2030.

In addition to mitigating the effects of climate change through carbon storage in woody biomass, urban trees offer a wide range of benefits, such as reducing the energy consumption of buildings, reducing urban heat, and improving subjective well-being. However, there are few empirical models to quantify the effect on building energy use, and existing data from St. Paul suggests that the effect may be small compared to the carbon sink effect. Additionally, several studies have shown socio-economic inequality in tree canopy coverage, making equity an essential consideration in the spatial planning of urban reforestation.

**GHG Impact Calculation**

$$ \text{Sequestered Carbon (in Mg CO_2 e)} = CD × A × 11/3 $$
*Where:*

-   $CD$ = Carbon stock density of urban trees in Mg/ha, a factor of aboveground biomass, (44.1 Mg C/ha, Nowak et al 2013), and belowground biomass to one meter (71 Mg C/ha, Pouyat et al. 20065) for a total stock density of 115.1 Mg C /ha.
-   $A$ = Increased area of tree canopy under tree planting scenarios, in hectares.
-   $11/3$ = Factor to convert Mg C to Mg CO2

```{r}

```



**RESOURCES**

- [Minnesota Department of Natural Resources: Urban forestry best management practices](https://www.dnr.state.mn.us/forestry/urban/bmps.html)
- [University of Minnesota Extension: Recommended trees for Minnesota](https://extension.umn.edu/tree-selection-and-care/recommended-trees-minnesota)
- [University of Minnesota Extension: Native urban trees of Southeast Minnesota](https://www.minnesotamasternaturalist.org/docs/invasive_blitz/native_urban_trees_of_se_mn.pdf)
- [Cities4Forests: Introduction to policy for urban forests](https://cities4forests.com/lg-urban-forests/introduction-to-policy-for-urban-forests/)

*Additional Information*

- [National Tree Benefit Calculator](http://www.treebenefits.com/calculator/)
- [Minneapolis Parks: Trees and the urban forest](https://www.minneapolisparks.org/park_care__improvements/trees/)
- [2020 Tree City USA Communities in Minnesota](https://www.dnr.state.mn.us/forestry/urban/tree-city-usa-awards.html#cities)
- [USDA: Urban forest data for Minnesota](https://www.nrs.fs.fed.us/data/urban/state/?state=MN)

**EXAMPLES**

Several cities are investing in large-scale tree planting programs as a means of decarbonization, including the Trillion Trees Initiative, the City of Los Angeles, the City of Tucson, and the City of Pittsburgh. In Minnesota, the City of Saint Paul 2011 Urban Canopy Assessment explored the potential for large-scale tree planting within the city.

**GROWING SHADE**

The Metropolitan Council, in partnership with the Nature Conservancy and the Tree Trust, has developed an online application called Growing Shade to help communities track and prioritize tree planting in areas with thin tree canopies. The app uses data from multiple sources, such as demographic information about neighborhoods, locations of businesses, schools, and parks, to create a detailed picture of a city at the neighborhood level. Nonprofits, cities, and communities can use the data to identify the best locations to plant trees, which can help to address issues such as high asthma rates, extreme temperatures, and the legacy of racial injustices.



