#### Retofit Existing Commercial Building 

Existing commercial buildings electrification.

::: about_strategy
***About this strategy*** Our assumption is that cities can promote a reduction in energy use intensity (EUI) that will result if `80%` of existing commercial buildings are certified as LEED Gold, which is assumed to reduce EUI by `25%`.
:::

```{r fig03b1, include=FALSE}

fig03b1_data <- full_join(
  non_res_bau_2018,
  non_res_bau_2040,
  by = "Variables") %>%
  full_join(
    .,
    run_scenario_building(
      run_residential = FALSE,
      run_non_residential = TRUE,
      .selected_ctu = params$ctu_selection,
      non_res_tb = building_data$non_residential,
      non_res_tb_bau = building_data$non_residential,
      .renewable_ng_nonres = FALSE,
      .electrified_buildings_pct = 0,
      .non_res_natural_gas_for_water_heating_pct = 0.20,
      .non_res_natural_gas_for_space_heating_pct = 0.69,
      .commercial_smart_grid_pct = 1,
      .industrial_smart_grid_pct = 1,
      .smart_grid_energy_reduction_pct = 1,
      .grid_decarbonization_pct = 0,
      .existing_high_efficiency_buildings_pct = 0.80,
      .enviro_factors = enviro_factors
    ) %>%
      ungroup() %>%
      dplyr::filter(
        year == 2040,
        scen == "scen",
        var %in% c(
          "commercial_mwh",
          "industrial_mwh",
          "commercial_therms",
          "industrial_therms",
          "total_industrial_commercial_emissions"
        )
      ) %>%
      add_variable_names(., "2040 Scenario"),
    by = "Variables"
  )

fig03b1_table <- fig03b1_data %>%
  # add table format
  tableformat(.,
              .caption = paste("Retrofit Commercial Buildings",
                               params$ctu_selection,
                               "2040"))
```

```{r echo=FALSE}
fig03b1_table
```

```{r}
chartformat(fig03b1_data)
```


