adj_fleet_shares(.bev_pct_sales = 20,
                 .phev_pct_sales = 15,
                 .hev_pct_sales = 40,
                 .pass_tb = transportation_data$passenger,
                 .freight_tb = transportation_data$freight,
                 .vmt_fee = 0,
                 .payd_fee = 0,
                 .gas_tax = 0,
                 .drs_pct_trip = 0,
                 .av_pct = 0,
                 .ctu,
                 .enviro_factors = enviro_factors)
