---
title: "output"
format: html
editor: visual
---

## Load Required Libraries

```{r}
library(ghg.sp)
library(tidyr)
library(tidyverse)

if (!requireNamespace("readxl", quietly = TRUE)) {
  install.packages("readxl")
}
if (!requireNamespace("dplyr", quietly = TRUE)) {
  install.packages("dplyr")
}
library(readxl)
library(dplyr)
```

## Run Scenario

```{r}
test <- ghg.sp::run_all_modules(
  .selected_ctu = "Minneapolis",
  run_land_use = TRUE,
  run_buildings = TRUE,
  run_residential = TRUE,
  run_non_residential = TRUE,
  run_transportation = TRUE,
  tb = land_use_data,
  non_res_tb = building_data$non_residential,
  res_tb = building_data$residential,
  res_tb_bau = building_data$residential,
  non_res_tb_bau = building_data$non_residential,
  pass_tb = transportation_data$passenger,
  freight_tb = transportation_data$freight,
  detail = FALSE,
  .renewable_ng_res = FALSE,
  .urban_form_scenario = "bau",
  .conservation_tillage_intervention = "current_conservation_tillage",
  .tree_planting_intervention = "tree_planting_on_all_pervious",
  .tree_planting_per_capita = 0.26,
  .tree_planting_per_hectare = 247,
  .parking_lot_reduction_percentage = 0.8,
  .electrified_buildings_pct = 0.4,
  .non_res_natural_gas_for_water_heating_pct = 0.2,
  .non_res_natural_gas_for_space_heating_pct = 0.69,
  .commercial_smart_grid_pct = 1,
  .industrial_smart_grid_pct = 1,
  .smart_grid_energy_reduction_pct = 1,
  .new_homes_to_multifamily_pct = 0.5,
  .existing_high_efficiency_buildings_pct = 0.8,
  .home_behavior_change_pct = 1,
  .single_family_floor_area_growth_pct = 0.05,
  .new_homes_affected_pct = 0.3,
  .new_homes_leed_gold_pct = 0.5,
  .existing_home_retrofit_pct = 0.8,
  .existing_home_ultra_retrofit_pct = 0.2,
  .res_natural_gas_for_space_heating_pct = 0.71,
  .res_natural_gas_for_water_heating_pct = 0.24,
  .additional_electrified_residential_buildings_pct = 0.45,
  .grid_decarbonization_pct = 1,
  .scenario = "BAU",
  .electric_scenario = "ER",
  .aeo_scenario = "REF",
  .transit_avo_pct = 0,
  .pldv_avo_pct = 0,
  .transit_service_pct = 0,
  .vmt_fee = 0,
  .payd_fee = 0,
  .gas_tax = 0,
  .parking_price = 0,
  .freight_parking_price = 0,
  .cong_price = 0,
  .freight_vmt_fee = 0,
  .drs_pct = 0,
  .av_pct = 0,
  .drs_fuel_type = "",
  .av_fuel_type = "",
  .pop_dens_pct_change = 0,
  .emp_dens_pct_change = 0,
  .land_use_diversity_pct_change = 0,
  .intersection_design_pct_change = 0,
  .job_access_pct_change = 0,
  .transit_dist_pct_change = 0,
  .comb_5d_impact_pct_change = 0,
  .telework_pct = 0,
  .bev_pct_sales = 0,
  .phev_pct_sales = 0,
  .hev_pct_sales = 0,
  .mit_bau_summary = 0,
  .enviro_factors = enviro_factors,
  .elast = elast,
  .elast_5d = elast_5d
)
```

```{r}
calc_tree_planting_land_cover(
  tb = land_use_data,
  detail = FALSE,
  .selected_ctu = "all",
  .urban_form_scenario = "bau",
  .tree_planting_intervention = "match_la_million_trees_goal",
  .tree_planting_per_capita = 0.26,
  .tree_planting_per_hectare = 247
)

calc_tree_planting_land_cover(
  tb = land_use_data,
  detail = FALSE,
  .selected_ctu = "all",
  .urban_form_scenario = "bau",
  .tree_planting_intervention = "double",
  .tree_planting_per_capita = 0.26,
  .tree_planting_per_hectare = 247
)
```
