---
title: "land_use_module"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{land_use_module}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ghg.gert)
```

```{r}
calc_land_cover_percentages(tb = land_use_data) %>%
  dplyr::filter(geog_name == "Lake Elmo")
```
```{r}
calc_land_by_development_type(
  tb = land_use_data,
  .urban_form_scenario = "bau"
) %>%
  dplyr::filter(geog_name == "Lake Elmo")
```
```{r}
calc_land_cover_by_land_use(
  tb = land_use_data,
  .urban_form_scenario = "bau"
) %>%
  dplyr::filter(geog_name == "Lake Elmo")
```
```{r}
calc_scen_land_use(
  tb = land_use_data,
  .urban_form_scenario = "bau"
) %>%
  dplyr::filter(geog_name == "Lake Elmo")
```
## Additional Strategies

```{r}
calc_tree_planting_land_cover(
  tb = land_use_data,
  detail = FALSE,
  .urban_form_scenario = "bau",
  .tree_planting_intervention = "match_la_million_trees_goal",
  .tree_planting_per_capita = 0.26,
  .tree_planting_per_hectare = 247
) %>%
  dplyr::filter(geog_name == "Lake Elmo")
```
```{r}
calc_parking_lot_land_cover(
  tb = land_use_data,
  .urban_form_scenario = "bau",
  .parking_lot_reduction_percentage = 0.8,
  .tree_planting_intervention = "tree_planting_on_all_pervious",
  .tree_planting_per_capita = 0.26,
  .tree_planting_per_hectare = 247,
  detail = FALSE
) %>%
  dplyr::filter(geog_name == "Lake Elmo")
```

```{r}
calc_conservation_tillage(
  tb = land_use_data,
  .urban_form_scenario = "bau",
  .conservation_tillage_intervention = "current_conservation_tillage",
  .tree_planting_intervention = "tree_planting_on_all_pervious",
  .tree_planting_per_capita = 0.26,
  .tree_planting_per_hectare = 247,
  .parking_lot_reduction_percentage = 0.8,
  detail = FALSE
) %>%
  dplyr::filter(geog_name == "Lake Elmo")
```
```{r}
ghg.gert::run_scenario_land_use(
  tb = land_use_data,
  .urban_form_scenario = "bau",
  .conservation_tillage_intervention = "current_conservation_tillage",
  .tree_planting_intervention = "tree_planting_on_all_pervious",
  .tree_planting_per_capita = 0.26,
  .tree_planting_per_hectare = 247,
  .parking_lot_reduction_percentage = 0.8,
  detail = FALSE
) %>%
  dplyr::filter(geog_name == "Lake Elmo")
```

