run_scenario_land_use <- function(tb = land_use_data.rda,
                                  .scenario = "bau",
                                  .luse_scen = "compact_dev_with_drs",
                                  .conservation_tillage_scen = "current_conservation_tillage",
                                  .tree_planting_intervention = "tree_planting_on_all_pervious",
                                  .w2w_diesel_emission_factor_kg_co2e_per_gal = 12.50,
                                  .avoided_emissions_tractor_use_mg_co2e_per_hectare = 0.0102,
                                  .agricultural_land_carbon_stock_mg_c_per_hectare = 3,
                                  .maximum_soc_accumation_under_reduced_or_no_till_ag = 1.54,
                                  .tree_planting_per_capita = 0.26,
                                  .tree_planting_per_hectare = 247,
                                  .parking_lot_reduction_percentage = 0.8,
                                  .impervious_sequest_mg_c_per_hectare_per_year = 0,
                                  .grass_sequest_mg_c_per_hectare_per_year = -0.42,
                                  .trees_sequest_mg_c_per_hectare_per_year = -1.27,
                                  .water_sequest_mg_c_per_hectare_per_year = 0,
                                  .barren_sequest_mg_c_per_hectare_per_year = -0.014,
                                  .forest_sequest_mg_c_per_hectare_per_year = -0.625,
                                  .shrub_sequest_mg_c_per_hectare_per_year = -0.287,
                                  .grassland_sequest_mg_c_per_hectare_per_year = -0.287,
                                  .agriculture_sequest_mg_c_per_hectare_per_year = -0.19,
                                  .woody_wetland_sequest_mg_c_per_hectare_per_year = -0.625,
                                  .wetland_sequest_mg_c_per_hectare_per_year = -1.493,
                                  .parking_lot_sequest_mg_c_per_hectare_per_year = 0,
                                  .impervious_stock_mg_c_per_hectare = 33,
                                  .grass_stock_mg_c_per_hectare = 77.04,
                                  .trees_stock_mg_c_per_hectare = 115,
                                  .water_stock_mg_c_per_hectare = 0,
                                  .barren_stock_mg_c_per_hectare = 5,
                                  .forest_stock_mg_c_per_hectare = 117,
                                  .shrub_stock_mg_c_per_hectare = 49,
                                  .grassland_stock_mg_c_per_hectare = 49,
                                  .agriculture_stock_mg_c_per_hectare = 41,
                                  .woody_wetland_stock_mg_c_per_hectare = 117,
                                  .wetland_stock_mg_c_per_hectare = 296.75,
                                  .parking_lot_stock_mg_c_per_hectare = 33,
                                  detail = FALSE){
  land_use <- scen_green_infrastructure(
    tb = tb,
    detail = detail,
    .luse_scen = .luse_scen,
    .conservation_tillage_scen = .conservation_tillage_scen,
    .w2w_diesel_emission_factor_kg_co2e_per_gal = .w2w_diesel_emission_factor_kg_co2e_per_gal,
    .avoided_emissions_tractor_use_mg_co2e_per_hectare = .avoided_emissions_tractor_use_mg_co2e_per_hectare,
    .agricultural_land_carbon_stock_mg_c_per_hectare = .agricultural_land_carbon_stock_mg_c_per_hectare,
    .maximum_soc_accumation_under_reduced_or_no_till_ag = .maximum_soc_accumation_under_reduced_or_no_till_ag,
    .tree_planting_intervention = .tree_planting_intervention,
    .tree_planting_per_capita = .tree_planting_per_capita,
    .tree_planting_per_hectare = .tree_planting_per_hectare,
    .parking_lot_reduction_percentage = .parking_lot_reduction_percentage,
    .impervious_sequest_mg_c_per_hectare_per_year = .impervious_sequest_mg_c_per_hectare_per_year,
    .grass_sequest_mg_c_per_hectare_per_year = .grass_sequest_mg_c_per_hectare_per_year,
    .trees_sequest_mg_c_per_hectare_per_year = .trees_sequest_mg_c_per_hectare_per_year,
    .water_sequest_mg_c_per_hectare_per_year = .water_sequest_mg_c_per_hectare_per_year,
    .barren_sequest_mg_c_per_hectare_per_year = .barren_sequest_mg_c_per_hectare_per_year,
    .forest_sequest_mg_c_per_hectare_per_year = .forest_sequest_mg_c_per_hectare_per_year,
    .shrub_sequest_mg_c_per_hectare_per_year = .shrub_sequest_mg_c_per_hectare_per_year,
    .grassland_sequest_mg_c_per_hectare_per_year = .grassland_sequest_mg_c_per_hectare_per_year,
    .agriculture_sequest_mg_c_per_hectare_per_year = .agriculture_sequest_mg_c_per_hectare_per_year,
    .woody_wetland_sequest_mg_c_per_hectare_per_year = .woody_wetland_sequest_mg_c_per_hectare_per_year,
    .wetland_sequest_mg_c_per_hectare_per_year = .wetland_sequest_mg_c_per_hectare_per_year,
    .parking_lot_sequest_mg_c_per_hectare_per_year = .parking_lot_sequest_mg_c_per_hectare_per_year,
    .impervious_stock_mg_c_per_hectare = .impervious_stock_mg_c_per_hectare,
    .grass_stock_mg_c_per_hectare = .grass_stock_mg_c_per_hectare,
    .trees_stock_mg_c_per_hectare = .trees_stock_mg_c_per_hectare,
    .water_stock_mg_c_per_hectare = .water_stock_mg_c_per_hectare,
    .barren_stock_mg_c_per_hectare = .barren_stock_mg_c_per_hectare,
    .forest_stock_mg_c_per_hectare = .forest_stock_mg_c_per_hectare,
    .shrub_stock_mg_c_per_hectare = .shrub_stock_mg_c_per_hectare,
    .grassland_stock_mg_c_per_hectare = .grassland_stock_mg_c_per_hectare,
    .agriculture_stock_mg_c_per_hectare = .agriculture_stock_mg_c_per_hectare,
    .woody_wetland_stock_mg_c_per_hectare = .woody_wetland_stock_mg_c_per_hectare,
    .wetland_stock_mg_c_per_hectare = .wetland_stock_mg_c_per_hectare,
    .parking_lot_stock_mg_c_per_hectare = .parking_lot_stock_mg_c_per_hectare
  )

  land_use_module_output <-
    land_use

  return(land_use_module_output)
}
