#' @title run all modules
#'
#' @param .selected_ctu Character. A string indicating the relevalnt CTU for running the modules.
#' @param run_land_use Boolean.
#' @param run_buildings Boolean.
#' @param run_transportation Boolean.
#' @inheritParams run_scenario_land_use
#' @inheritParams run_scenario_building
#' @inheritParams run_scenario_transportation
#' @return List. Return a list with the outputs of the three modules.
#' @export

run_all_modules <- function(.selected_ctu = "all",
                            run_land_use = TRUE,
                            run_buildings = TRUE,
                            run_residential = TRUE,
                            run_non_residential = TRUE,
                            run_transportation = TRUE,
                            tb = land_use_data,
                            non_res_tb = building_data$non_residential,
                            res_tb = building_energy_bau_data$residential,
                            res_tb_bau = building_energy_bau_data$residential,
                            non_res_tb_bau = building_data$non_residential,
                            pass_tb = transportation_data$passenger,
                            freight_tb = transportation_data$freight,
                            detail = FALSE,
                            .renewable_ng_res = FALSE,
                            .urban_form_scenario = "bau",
                            .conservation_tillage_intervention = "current_conservation_tillage",
                            .tree_planting_intervention = "tree_planting_on_all_pervious",
                            .tree_planting_per_capita = 0.26,
                            .tree_planting_per_hectare = 247,
                            .parking_lot_reduction_percentage = 0.8,
                            .electrified_buildings_pct = 0.40,
                            .non_res_natural_gas_for_water_heating_pct = 0.20,
                            .non_res_natural_gas_for_space_heating_pct = 0.69,
                            .commercial_smart_grid_pct = 1.00,
                            .industrial_smart_grid_pct = 1.00,
                            .smart_grid_energy_reduction_pct = 1.00,
                            .new_homes_to_multifamily_pct = 0.50,
                            .existing_high_efficiency_buildings_pct = 0.80,
                            .home_behavior_change_pct = 1.00,
                            .single_family_floor_area_growth_pct = 0.05,
                            .new_homes_affected_pct = 0.30,
                            .new_homes_leed_gold_pct = 0.50,
                            .existing_home_retrofit_pct = 0.80,
                            .existing_home_ultra_retrofit_pct = 0.20,
                            .res_natural_gas_for_space_heating_pct = 0.71,
                            .res_natural_gas_for_water_heating_pct = 0.24,
                            .additional_electrified_residential_buildings_pct = 0.45,
                            .grid_decarbonization_pct = 1,
                            .scenario = "BAU",
                            .electric_scenario = "ER",
                            .aeo_scenario = "REF",
                            .transit_avo_pct = 0,
                            .pldv_avo_pct = 0,
                            .transit_service_pct = 0,
                            .vmt_fee = 0,
                            .payd_fee = 0,
                            .gas_tax = 0,
                            .parking_price = 0,
                            .freight_parking_price = 0,
                            .cong_price = 0,
                            .freight_vmt_fee = 0,
                            .drs_pct = 0,
                            .av_pct = 0,
                            .drs_fuel_type = "",
                            .av_fuel_type = "",
                            .pop_dens_pct_change = 0,
                            .emp_dens_pct_change = 0,
                            .land_use_diversity_pct_change = 0,
                            .intersection_design_pct_change = 0,
                            .job_access_pct_change = 0,
                            .transit_dist_pct_change = 0,
                            .comb_5d_impact_pct_change = 0,
                            .telework_pct = 0,
                            .bev_pct_sales = 0,
                            .phev_pct_sales = 0,
                            .hev_pct_sales = 0,
                            .mit_bau_summary = 0,
                            .enviro_factors = enviro_factors,
                            .elast = elast,
                            .elast_5d = elast_5d
                            ) {

  if (run_land_use == TRUE) {
    land_use <- run_scenario_land_use(
      tb = tb,
      .selected_ctu = .selected_ctu,
      .urban_form_scenario = .urban_form_scenario,
      .conservation_tillage_intervention = .conservation_tillage_intervention,
      .tree_planting_intervention = .tree_planting_intervention,
      .tree_planting_per_capita = .tree_planting_per_capita,
      .tree_planting_per_hectare = .tree_planting_per_hectare,
      .parking_lot_reduction_percentage = .parking_lot_reduction_percentage,
      detail = detail
    )
  }
 if (run_buildings == TRUE) {
  buildings <- run_scenario_building(
    res_tb = res_tb ,
    non_res_tb = non_res_tb,
    res_tb_bau = res_tb_bau ,
    non_res_tb_bau = non_res_tb_bau,
    run_residential = run_residential ,
    run_non_residential = run_non_residential,
    .selected_ctu = .selected_ctu,
    .electrified_buildings_pct = .electrified_buildings_pct,
    .non_res_natural_gas_for_water_heating_pct = .non_res_natural_gas_for_water_heating_pct,
    .non_res_natural_gas_for_space_heating_pct = .non_res_natural_gas_for_space_heating_pct,
    .commercial_smart_grid_pct = .commercial_smart_grid_pct,
    .industrial_smart_grid_pct = .industrial_smart_grid_pct,
    .smart_grid_energy_reduction_pct = .smart_grid_energy_reduction_pct,
    .new_homes_to_multifamily_pct = .new_homes_to_multifamily_pct,
    .existing_high_efficiency_buildings_pct = .existing_high_efficiency_buildings_pct,
    .home_behavior_change_pct = .home_behavior_change_pct,
    .single_family_floor_area_growth_pct = .single_family_floor_area_growth_pct,
    .new_homes_affected_pct = .new_homes_affected_pct ,
    .new_homes_leed_gold_pct = .new_homes_leed_gold_pct,
    .existing_home_retrofit_pct = .existing_home_retrofit_pct,
    .existing_home_ultra_retrofit_pct = .existing_home_ultra_retrofit_pct,
    .res_natural_gas_for_space_heating_pct = .res_natural_gas_for_space_heating_pct,
    .res_natural_gas_for_water_heating_pct = .res_natural_gas_for_water_heating_pct,
    .additional_electrified_residential_buildings_pct = .additional_electrified_residential_buildings_pct,
    .grid_decarbonization_pct = .grid_decarbonization_pct,
    .enviro_factors = .enviro_factors
  )}
 if (run_transportation == TRUE) {
  transp <- run_scenario_transportation(
    pass_tb = pass_tb,
    freight_tb = freight_tb ,
    .selected_ctu = .selected_ctu,
    .scenario = .scenario ,
    .electric_scenario = .electric_scenario ,
    .aeo_scenario = .aeo_scenario ,
    .transit_avo_pct = .transit_avo_pct,
    .pldv_avo_pct = .pldv_avo_pct,
    .transit_service_pct = .transit_service_pct,
    .vmt_fee = .vmt_fee ,
    .payd_fee = .payd_fee ,
    .gas_tax = .gas_tax ,
    .parking_price = .parking_price,
    .freight_parking_price = .freight_parking_price,
    .cong_price = .cong_price,
    .freight_vmt_fee = .freight_vmt_fee,
    .drs_pct = .drs_pct,
    .av_pct = .av_pct,
    .drs_fuel_type = .drs_fuel_type,
    .av_fuel_type = .av_fuel_type,
    .pop_dens_pct_change = .pop_dens_pct_change,
    .emp_dens_pct_change = .emp_dens_pct_change,
    .land_use_diversity_pct_change = .land_use_diversity_pct_change,
    .intersection_design_pct_change = .intersection_design_pct_change,
    .job_access_pct_change = .job_access_pct_change,
    .transit_dist_pct_change = .transit_dist_pct_change,
    .comb_5d_impact_pct_change = .comb_5d_impact_pct_change ,
    .telework_pct = .telework_pct,
    .bev_pct_sales = .bev_pct_sales,
    .phev_pct_sales = .phev_pct_sales,
    .hev_pct_sales = .hev_pct_sales,
    .mit_bau_summary = .mit_bau_summary ,
    .elast = elast,
    .elast_5d = elast_5d,
    .enviro_factors = enviro_factors
  )
  }
}
